### ISSUE TITLE
Login.jsp not working

### ISSUE THREAD

**Issue by mapgrady** [Internet2/Shibboleth-Multi-Context-Broker#25]
We configured the MCB latest distribution (1.2.5) into a Shibboleth IdP 2.4.4, along with the Duo plugin for it. We configured the initial context login page to be a JSP (login.jsp). Then we set up a test to force Duo authentication. The MCB gets control, sends the user to the login page correctly for initial authentication, but is then just giving control back to the IdP and not running the 2nd leg of authentication with Duo. With the exact same config and test, just changing the login page config to be the sample Velocity template for such, our test works as expected, going on to Duo after the login is completed. So a bug has been introduced at some point in the last few MCB releases that has broken support for a JSP-based login page. (Separately shared an idp-process log with Paul Hethmon illustrating the failure.)

**Comment by paulhethmon** [comment]
Waiting on info from Mike Grady. Request sent via private email.

**Comment by mapgrady** [comment]
Issue was resolved, it was a misconfiguration related to the JSP.
